version: '3.8'

services:
  hello-world:
    image: hello-world
    container_name: hello-world-container

  app:
    build:
      context: ./
    container_name: task3-app
    ports:
      - "8081:8080"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: task3
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
