apiVersion: apps/v1
kind: Deployment
metadata:
  name: task3-app-deployment
  labels:
    app: task3-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task3-app
  template:
    metadata:
      labels:
        app: task3-app
    spec:
      containers:
        - name: task3-app
          image: 4functionaltests/devops-task3:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: task3-app-service
spec:
  type: NodePort
  selector:
    app: task3-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001